name: Continuous Integration

on:
  push:
    branches: [ patch-linux4.7 ]
  pull_request:
    branches: [ patch-linux4.7 ]

jobs:

  # NOTE(antoineco): This job only tests that the module builds on whatever
  # kernel version the GitHub Actions runner is running:
  # https://github.com/actions/virtual-environments/blob/ubuntu20/20220425.1/images/linux/Ubuntu2004-Readme.md
  #
  # Ideally, we would be able to select one runner for each kernel version we
  # intend to support, but this likely requires deploying self-hosted runners.
  #
  build:
    name: Build Kernel Module
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build wl module
      run: make

    - name: Clean wl module
      if: always()
      run: make clean
